import Head from "next/head";
import Carousel from "@/components/Carousel";
import About from "@/components/About";
import Subject from "@/components/Subject";
import Classes from "@/components/Classes";
import Registration from "@/components/Registration";
import Team from "@/components/Team";
import Testimonial from "@/components/Testimonial";
import News from "@/components/NewsContainer";
import prisma from "@/lib/prisma";

export const getStaticProps = async () => {
  const subjects = await prisma.subject.findMany({
    include: {
      classes: true,
    },
  });
  return {
    props: { subjects },
    revalidate: 10,
  };
};

export default function Home({ subjects }) {
  console.log(subjects);
  return (
    <>
      <Head>
        <title>SunRoad</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Carousel />
      <About />
      <Subject subjects={subjects} />
      <Classes />
      <Registration />
      <Team />
      <Testimonial />
      <News />
    </>
  );
}
