import Head from "next/head";
import Carousel from "@/components/Carousel";
import About from "@/components/About";
import Subject from "@/components/Subject";
import Classes from "@/components/Classes";
import Registration from "@/components/Registration";
import Team from "@/components/Team";
import Testimonial from "@/components/Testimonial";
import News from "@/components/NewsContainer";
import { Data } from "@/context";

import { useContext } from "react";

export default function Home() {
  const { message: subjects } = useContext(Data);
  let classes = [];
  subjects?.map((subject) => (classes = [...classes, ...subject.classes]));

  return (
    <>
      <Head>
        <title>SunRoad</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Carousel />
      <About />
      <Subject subjects={subjects} />
      <div className="text-center mb-5">
        <h5
          className="text-primary text-uppercase mb-3"
          style={{ letterSpacing: "5px" }}
        >
          Các lớp học của chúng tôi
        </h5>
        <h1>Rất nhiều đánh giá tích cực</h1>
      </div>
      <Classes classes={classes.slice(0, 5)} />
      <Registration classes={classes} />
      <Team />
      <Testimonial />
      <News />
    </>
  );
}
