import Head from "next/head";
import Carousel from "@/components/Carousel";
import About from "@/components/About";
import Category from "@/components/Category";
import Courses from "@/components/Courses";
import Registration from "@/components/Registration";
import Team from "@/components/Team";
import Testimonial from "@/components/Testimonial";
import News from "@/components/News";

export default function Home() {
  return (
    <>
      <Head>
        <title>SunRoad</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Carousel />
      <About />
      <Category />
      <Courses />
      <Registration />
      <Team />
      <Testimonial />
      <News />
    </>
  );
}
